### ISSUE TITLE
cannot create class "org.anathan.zf2modulecreator.NewModuleAction" [Plugin: org.anathan.zf2modulecreator]

### ISSUE THREAD

**Issue by xeras** [anathan2586/zf2modulecreator#1]
cannot create class "org.anathan.zf2modulecreator.NewModuleAction" [Plugin: org.anathan.zf2modulecreator]
com.intellij.diagnostic.PluginException: cannot create class "org.anathan.zf2modulecreator.NewModuleAction" [Plugin: org.anathan.zf2modulecreator]
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:175)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:531)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:511)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:488)
    at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:354)
    at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:312)
    at com.intellij.ide.actions.WeighingActionGroup.getChildren(WeighingActionGroup.java:61)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1324)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1317)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:1317)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:1332)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1311)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.c(ActionManagerImpl.java:1301)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.access$200(ActionManagerImpl.java:75)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$4.run(ActionManagerImpl.java:1282)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: com.intellij.diagnostic.PluginException: org/anathan/zf2modulecreator/NewModuleAction : Unsupported major.minor version 51.0 [Plugin: org.anathan.zf2modulecreator]
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:151)
    ... 23 more
Caused by: java.lang.UnsupportedClassVersionError: org/anathan/zf2modulecreator/NewModuleAction : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:465)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:213)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:209)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:185)
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
    ... 29 more

**Comment by zero0000zero** [comment]
Hi xeras,

What version of PhpStorm / IntelliJ are you using?

Regards,
Alan

**Comment by xeras** [comment]
8.0.3

**Comment by zero0000zero** [comment]
I got different NoClassDefError in PhpStorm 8 and fixed it.
Can you try out v0.2.1, see if that fixes for you?

**Comment by zero0000zero** [comment]
(Use the jar in GitHub release)

**Comment by saadhre** [comment]
Still can reproduce with PhpStorm 8.0.3 and plugin version 0.2.1 (installed from GitHub release).

**Comment by zero0000zero** [comment]
Suppose it doesn't work when with this error.
What OS and JVM do you use?

**Comment by saadhre** [comment]
OS: OS X Yosemite (10.10.3)
JVM:

```
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
```

**Comment by apoca** [comment]
I have same issue: 00:00:38 PluginException: cannot create class "org.anathan.zf2modulecreator.NewModuleAction" [Plugin: org.anathan.zf2modulecreator]

**Comment by zero0000zero** [comment]
Can you try v0.2.2beta? https://github.com/anathan2586/zf2modulecreator/releases/tag/v0.2.2beta

**Comment by apoca** [comment]
Yes... 

16:07:31 PluginException: class with name "org.anathan.zf2modulecreator.NewModuleAction" not found [Plugin: org.anathan.zf2modulecreator]

**Comment by saadhre** [comment]
Same here with 0.2.2beta

**Comment by saadhre** [comment]
Working in PhpStorm 9.0 (plugin version: 0.2.1).
